Algoritmo "Atv14"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Ler um valor maior que 10
// Autor(a)    :Breno
// Data atual  : 24/03/2023
Var
   valor: inteiro

Inicio
   Escreva("Digite um valor: ")
   Leia(valor)

   Se (valor > 10) Então
      Escreva("É MAIOR QUE 10!")
   Senão
      Escreva("NÃO É MAIOR QUE 10!")
   FimSe

Fimalgoritmo