Algoritmo "Carro"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Calculo do valor final
// Autor(a)    : Breno Correa
// Data atual  : 16/03/2023
Var
//
precodeFabrica: real
precoFinal: real
Inicio
//
escreval("Preço De Fábrica")
leia(precodeFabrica)
precoFinal<-45/100*precodeFabrica + 28/100*precodeFabrica
escreval("Preço Final")
Fimalgoritmo